version: "3.1"

services:
  api:
    image: timestamper
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./timestamper_db_store:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  timestamer_db_store:
    external: true
