version: "3.1"

services:
  api:
    image: timestamper
    build:
      context: .
      dockerfile: ./app/Dockerfile
    depends_on:
      - postgres

  postgres:
    image: postgres:bullseye
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

